name: "Create version number"

description: "Create version number based on git commit"

inputs:
  path:
    description: "Path of Maven Project, default ./"
    required: false

runs:
  using: "composite"
  steps:
    - name: Fetch all history for all tags and branches
      shell: bash
      run: git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.0.1
      with:
        versionSpec: "6.3.x"

    - name: Execute GitVersion
      uses: gittools/actions/gitversion/execute@v4.0.1

    - name: Helm tool installer
      uses: Azure/setup-helm@v4.3.0

    - name: Restore kubeconfig
      shell: bash
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Create version
      shell: bash
      run: $GITHUB_ACTION_PATH/deploy.sh
