name: "Docker Image Build ghcr"

description: "Docker Image Build and upload to ghcr"

inputs:
  path:
    description: "Path of Maven Project, default ./"
    required: false
  username:
    description: "Username used to log against the Docker registry"
    required: true
  password:
    description: "Password or personal access token used to log against the Docker registry"
    required: true
  github_token:
    description: "The secrets that you create are available to use in GitHub Actions workflows"
    required: true

runs:
  using: "composite"
  steps:
    - name: Test Docker is installed
      shell: bash
      env:
        WORK_DIR: ${{ inputs.path }}
        REGISTRY: ghcr.io
        BRANCH: ${{ github.head_ref || github.ref_name }} 
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        IMAGE_NAME: ${{ github.repository }}
      run: $GITHUB_ACTION_PATH/build.sh

    - name: Removing login credentials for "ghcr.io"
      if: always()
      shell: bash
      run: $GITHUB_ACTION_PATH/post.sh

