name: "Docker Image Build ghcr"

description: "Docker Image Build and upload to ghcr"

inputs:
  path:
    description: "Path of Maven Project, default ./"
    required: false
  username:
    description: "Username used to log against the Docker registry"
    required: true
  password:
    description: "Password or personal access token used to log against the Docker registry"
    required: true
  registry:
    description: "Docker Push registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Test Docker is installed
      shell: bash
      env:
        SHA: ${{ github.sha }}
        WORK_DIR: ${{ inputs.path }}
        REGISTRY: ${{ input.registry }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        IMAGE_NAME: ${{ github.repository }}
        BRANCH: ${{ github.head_ref || github.ref_name }} 
      run: $GITHUB_ACTION_PATH/build.sh

    - name: Removing login credentials for ${{ input.registry }}
      if: always()
      shell: bash
      env:
        REGISTRY: ${{ input.registry }}
      run: $GITHUB_ACTION_PATH/post.sh

