name: Bun Test 🧪

on:
  push:
    branches:
      - main
      - feature-bunTest
    paths:
      - "test/bun/**"
      - ".github/workflows/bunTest.yaml"

jobs:
  bunTest:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    name: Maven Test
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: KAnggara/DevOps/test/bun@feature-bunTest
        with:
          path: action_test/bun
