name: LCOV Coverage Analysis

on:
  push:
    branches:
      - main
    paths:
      - "lcov/**"
      - "test/bun/coverage/**"
      - ".github/workflows/lcov.yaml"
  workflow_dispatch:

jobs:
  lcov:
    runs-on: ubuntu-24.04
    name: Lcov Test
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: KAnggara/DevOps/lcov@v0.1.17
        with:
          coverage-files: coverage/lcov.info
          working-dir: action_test/bun
